name: Web Developer
ref: web-developer
description: Tools to work with React on the frontend and Go on the backend
version: 1.0.0
maintainers: []
tools:
  - name: pnpm
  - name: go
  - name: nodejs
  - name: go_air